# 数组 Array

数组(array)是一种多维的向量，其内部存储方式和向量一样，但是数组的显示和访问方式有所不同。数组对象可被认为是具有维度属性的向量：

In [6]:
a <- array(c(1:12), dim=c(2, 2, 3))
a

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

In [7]:
a[,,2]

[,1] [,2]
[1,] 5    7   
[2,] 6    8