# 基础

## 函数 Function

在R中，完成所有工作的操作都被称为函数。

In [1]:
exp(1)
cos(3.1415693)
log2(1)

[1] 2.718282

[1] -1

[1] 0

有些函数需要多个参数，可以通过参数名来为其赋值，也可以按照默认顺序传入参数：

In [2]:
log(x=64, base=4)
log(64, 4)

[1] 3

[1] 3

操作符也是函数：

In [3]:
17 + 2
2 ^ 10
3 == 4

[1] 19

[1] 1024

[1] FALSE

## 变量 Variables

### 赋值

In [4]:
x <- 1
y <- 2
z <- c(x, y)
z

[1] 1 2

代换过程是在z被赋值时已经完成，而不是在对z进行求值时

In [5]:
y <- 4
z

[1] 1 2

"="操作符等同于"<-"，把右边的值赋给左边的符号，"->" 操作符把左边的值赋给右边的符号：

In [6]:
x = 4
6 -> y
c(x, y)

[1] 4 6

函数也可以作为一个对象赋值给一个符号。

In [7]:
f <- function(x, y){ c(x+1, y+1) }
f(1, 2)
f

[1] 2 3

function(x, y){ c(x+1, y+1) }

注意：函数的参数赋值不能使用 <- 操作符，只能使用"="。

## 数据结构

数组(array)是一种多维的向量，其内部存储方式和向量一样，但是数组的显示和访问方式有所不同。数组对象可被认为是具有维度属性的向量：

In [8]:
a <- array( c(1:12), dim=c(3, 4))
a

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

通过下标来取其中的元素：

In [9]:
a[2, 2]

[1] 5

In [10]:
a[1:2, 1:2]

[,1] [,2]
[1,] 1    4   
[2,] 2    5

取一个或多个维度的全部元素：

In [11]:
a[1,]
a[,1]

[1]  1  4  7 10

[1] 1 2 3

In [12]:
a[c(1,3),]

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 3    6    9    12

具有相同类型元素的向量：

In [13]:
v <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
v

[1]  1  2  3  4  5  6  7  8  9 10

矩阵是一种二位数组：

In [14]:
m <- matrix(data=c(1:12), nrow=3, ncol=4)
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

数组也可以具有两个以上维度：

In [15]:
w <- array(c(1:18), dim=c(3,3,2))
w
w[1, 1, 1]

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

[1] 1

R 有一种内置的数据类型，可以混合多种不同类型的对象，它就是列表（list）。

In [17]:
e <- list(thing="hat", size="8.25")
e

$thing
[1] "hat"

$size
[1] "8.25"

In [18]:
e$thing
e[1]
e[[1]]

[1] "hat"

$thing
[1] "hat"

[1] "hat"

数据框(data frame)是一种特殊的列表，它可以包含多个具有相同长度的向量作为其元素，每个元素相当于一个列，都具有列名。数据框和电子表格或者数据库中的二维表很相似。
下面是一个棒球比赛数据的例子：

In [19]:
teams <- c("PHI", "NYM", "FLA", "ATL", "WSN")
w <- c(92, 89, 94, 72, 59)
l <- c(70, 73, 77, 90, 102)
nleast <- data.frame(teams, w, l)
nleast

teams w  l  
1 PHI   92  70
2 NYM   89  73
3 FLA   94  77
4 ATL   72  90
5 WSN   59 102

使用$操作符通过列名取数据框中的元素：

In [21]:
nleast$teams

[1] PHI NYM FLA ATL WSN
Levels: ATL FLA NYM PHI WSN

在数据框中还可以搜寻某个特定的值。条件搜寻返回一个布尔向量：

In [23]:
nleast$teams=="FLA"

[1] FALSE FALSE FALSE FALSE  TRUE

搜寻某队的负场数：

In [26]:
nleast$l[nleast$teams=="FLA"]

[1] 102