# Matrix

使用矩阵表示

向量转化为矩阵

In [ ]:
matrix(c(1,3,9,8,9,80,1,4,2,7,88,1,22,21,31,2,44,9,10,9,10), nrow=3, ncol=7, byrow=TRUE)

In [ ]:
matrix(c(1,4,31,3,2,2,9,7,44,8,88,9,9,1,10,80,22,9,1,21,10), nrow=3, ncol=7, byrow=FALSE)

为矩阵添加名称dimnames参数

In [ ]:
matrix(c(1,4,31,3,2,2,9,7,44,8,88,9,9,1,10,80,22,9,1,21,10), ncol=7,
       dimnames=list(c("row1", "row2", "row3"),
                     c("col1", "col2", "col3", "col4", "col5", "col6", "col7")))

In [ ]:
m <- matrix(c(1,4,31,3,2,2,9,7,44,8,88,9,9,1,10,80,22,9,1,21,10), nrow=3, ncol=7, byrow=FALSE)
rownames(m) <- c("row1", "row2", "row3")
colnames(m) <- c("col1", "col2", "col3", "col4", "col5", "col6", "col7")
m

In [ ]:
m[1,]

In [ ]:
m[,1]

In [ ]:
m[,"col2"]

In [ ]:
空矩阵

In [ ]:
a <- matrix(0, nrow=3, ncol=5)
a

矩阵扩展

In [ ]:
cbind(a, c(1,1,2))

In [ ]:
rbind(a, c(1:5))

矩阵合并

In [ ]:
a <- matrix(1:6, 3, 2)
b <- matrix(7:12, 3, 2)

In [ ]:
cbind(a, b)

In [ ]:
rbind(a, b)

矩阵变为向量

In [ ]:
as.vector(a)

In [ ]:
b <- matrix(a)
b

矩阵apply()运算函数

语法是apply(data, dim, function),dim取1表示对行运用函数，取2表示对列运用函数。

In [ ]:
x <- matrix(1:6, 2, 3)

colMeans(x) # 列均值
colSums(x)  # 列和

In [ ]:
apply(x, 2, mean) # 列均值，等同于colMeans(xx)
apply(x, 2, sum)  # 列和，等同于colMeans(xx)，所以矩阵行和列的运算推荐用apply()。
apply(x, 1, var)  # 行方差
apply(x, 2, max)  # 每列最大值
apply(x, 2, rev)  # 每列的数反排列

In [42]:
apply(x, 2, length)
max(apply(x, 2, length))

[1] 2 2 2

[1] 2

In [44]:
apply(x, 2, unique)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## 矩阵计算

### 矩阵转置

In [3]:
m <- matrix(1:12, c(3, 4))
m
t(m)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [16]:
m1 <- matrix(rep(1, 6), c(2, 3))
m2 <- matrix(c(1, 0, 1, 0, 1, 0), c(2, 3))
m2
m1 & m2

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 0    0    0

[,1]  [,2]  [,3] 
[1,]  TRUE  TRUE  TRUE
[2,] FALSE FALSE FALSE