# Vector

在 R 中所有输入的数值都会被认为是向量 (*vector*)，向量是一组有序数字的集合。
一维数据, 只能存放同一类型的数据
访问的时候下标从1开始; 向量里面只能存放相同类型的数据.

## 初始化

可以使用 c(...) 函数（c表示合并 combine）来构建向量。

In [1]:
a <- c(1, 2, 5, 3, 6, -2, 4)
b <- c("one", "two", "three")
c <- c(T, T, T, F, T, F)

x <- rep(2, 10)
y <- seq(1, 5, by=0.5)
z <- seq(from=1, length=10, by=0.5)

is.vector(a)

[1] TRUE

In [2]:
v <- c(1,"zhao")
v[1]

[1] "1"

这里面有integer和字符串, 整数自动转化成了字符

In [11]:
length(x)

[1] 5

### 命名


In [14]:
# Poker winnings from Monday to Friday:
poker.vector <- c(140, -50, 20, -120, 240)

# Roulette winnings form Monday to Friday:
roulette.vector <- c(-24, -50, 100, -350, 10)

# 给vector命名 
names(poker.vector) <- names(roulette.vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

poker.vector
roulette.vector

Monday   Tuesday Wednesday  Thursday    Friday 
      140       -50        20      -120       240

Monday   Tuesday Wednesday  Thursday    Friday 
      -24       -50       100      -350        10


## 访问

### 通过整数向量引用

使用方括号 x[s] 可以根据元素位置在向量中查找元素，s 可以是一个整数向量来查找单个或多个向量元素。

In [3]:
x <- c(1:8)
x[2]
x[c(2, 4)]
x[c(1, 3, 5)]
x[c(2:6)]      # 显示2-6元素

[1] 2

[1] 2 4

[1] 1 3 5

[1] 2 3 4 5 6

使用负整数返回一个删除了特定元素的向量：

In [4]:
x[-5]
x[-(1:2)]
x[-3:-1]

[1] 1 2 3 4 6 7 8

[1] 3 4 5 6 7 8

[1] 4 5 6 7 8

### 通过逻辑向量引用

#### 条件

In [16]:
x <- c(1:8)
x > 3

[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

In [18]:
# 返回所有等于 3 的元素
x[x==3]

# 返回 3 的倍数
x[(x %% 3) == 0]

# 返回所有大于 5 的元素
x[(x > 3)]

[1] 3

[1] 3 6

[1] 4 5 6 7 8

索引向量不必与向量本身长度相同，R 会自行重复长度较短的向量并返回匹配的值

In [19]:
x[c(T,F,F,T)]

[1] 1 4 5 8

### which

which返回的是元素下标

In [7]:
x <- c(1:8)
x[which(x>5)]
x[which.min(x)]
x[which.max(x)]

[1] 6 7 8

[1] 1

[1] 8

### match 匹配

In [8]:
b <- c(11,12,13,14,15,16,17,18,19,20)
c(11,21) %in% b
d <- c(11, 21)
match(d, b)

[1]  TRUE FALSE

[1]  1 NA

## 操作

In [9]:
x <- c(2, 4, 6, 8, 10)
x + 2
x * 2
1/x

[1]  4  6  8 10 12

[1]  4  8 12 16 20

[1] 0.5000000 0.2500000 0.1666667 0.1250000 0.1000000

In [10]:
a <- c(1:10)
b <- letters[1:10]
v <- c(a, b)
v

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "a"  "b"  "c"  "d"  "e" 
[16] "f"  "g"  "h"  "i"  "j"

In [10]:
c <- c(1:12)
c
min(c)
max(c)
sum(c)
prod(c)
mean(c)
var(c)

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1] 1

[1] 12

[1] 78

[1] 479001600

[1] 6.5

[1] 13

In [37]:
m <- matrix(rep(0, 12), c(3, 4))
m
v <- c(T, F, T, F)
m[, c(T, F, T, F)]=1
m
m <- matrix(rep(0, 12), c(3, 4))
m[c(T, F, T), ]=1
m

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0

[,1] [,2] [,3] [,4]
[1,] 1    0    1    0   
[2,] 1    0    1    0   
[3,] 1    0    1    0

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 0    0    0    0   
[3,] 1    1    1    1